# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Domitille Coq--Etchegaray
title: PhD student
email: domitille.coq-etchegaray@inrae.fr / domitille.coqetchegaray@gmail.com
# website: this beautiful one

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: dcoqetchegaray
github_username:  dcoqetc
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profiles.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Domitille and I'm a PhD student working on the genetic basis of plant specialized metabolites variation in two model species sessile oak and bread wheat. 
  
  I'm looking for a postdoc position :)    
  
  In my project:    
    1) I study the genetic basis of leaf specialized metabolites variation within sessile oak populations using genome-wide association approaches with genomic and metabolomic data.   
    2) I study specialized metabolites gene expression response induced by the infection of *Fusarium graminearum* in modern bread wheat cultivars using transcriptomic data. I also study the potential role of gene expression variation between homoeolog genes copies in differentiated gene expression response among cultivars to the infection.  

  **Keywords**: population genomics, genome-wide association analysis, evolution bioinformatics    
  **Programming Skills**: R, Python, Unix, Snakemake, Singularity, Slurm-HPCs, Git    

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PhD student (INRAe)
        sub_title: UMR BIOGECO (Cestas) - UMR GDEC (Clermont-Ferrand) FRANCE
        link: http://www.theses.fr/s258031
        caption: December 2020 - Decembre 2023
        description: |
          <u>PhD Subject</u>: Genetic bases of specialized metabolites variation and effect on biotic interactions in a major crop (*Triticum aestivum*) and a dominant forest tree (*Quercus petraea*).

          [![biogeco](images/Logo-Biogeco_inra_logo.png)](https://www6.bordeaux-aquitaine.inrae.fr/biogeco)  [<img src="images/Bandeau-accueil_inra_bandeau_home_nh.png" alt="drawing" width="30%"/>](https://www6.clermont.inrae.fr/umr1095)
          
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
  - title: Preprints & Publications
    layout: list
    content:
      - layout: left
        title: Preprint
        sub_title: bioRxiv
        description: |
          [Extensive genetic variation of leaf specialized metabolites in sessile oak (*Quercus petraea*) populations.](https://doi.org/10.1101/2023.04.07.536008)
      - layout: left
        title: In preparation
        description: |
          Differentiated homoeolog expression bias of specialized metabolites-related genes among five modern bread wheat (*Triticum aestivum*) cultivars to the infection of *Fusarium graminearum* 
  - title: Conference presentations
    layout: list
    content:
      - layout: left
        title: Young researchers days  
        link: https://eng-jjc2023.journees.inrae.fr/
        sub_title: 03-05 April 2023 Clermont-Ferrand, France
        description: | 
          **Member of the organizing commitee**   
          **Poster**: Differentiated gene expression response of specialized metabolites-related genes among five modern bread wheat (*Triticum aestivum*) cultivars to the infection of *Fusarium graminearum*
      - layout: left
        title: Symposium Future PhDs for Future Forests
        link: https://www.evoltree.eu/training/item/symposium-future-phds-for-future-forests
        sub_title: 28-30 September 2022 Göttingen, Germany
        caption: Science & Environment Department mobility grant, Univerity of Bordeaux
        description: | 
          **Talk title**: Genetic architecture of leaf specialized metabolites in sessile oak (*Quercus petraea*)
      - layout: left
        title: ESEB Conference
        link: https://www.eseb2022.cz/
        sub_title: 14-19 August 2022 Prague, Czech Republic
        caption: EVOLTREE Conference Grant
        description: | 
          **Talk title**: Genetic architecture of leaf specialized metabolites in sessile oak (*Quercus petraea*)
      - layout: left
        title: EVOLTREE Conference
        link: https://www.evoltree.eu/conferences/conference/first-evoltree-conference-2021
        caption: 14-17 September 2021, Online
        description: | 
          **Talk title**: Genome-wide association study of leaf specialized metabolites in sessile oak (*Quercus petraea*) provenances.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: PhD - Evolutionary, Functional & Community Ecology
        caption: 2020 - present
        sub_title: University of Bordeaux
      - layout: top
        title: Master of Science degree in Bioinformatics
        caption: 2018-2020
        sub_title: University of Bordeaux
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
